### ISSUE TITLE
groopM not functional after installation

### ISSUE THREAD

**Issue by jvollme** [minillinim/GroopM#5]
somehow i managed to install groopM. However, the installation isnot functional.
First of all, it seems GroopM is using outdated pytables syntax, and i cant install the old pytables version required for that because of numerous compatibilty problems in the conda and pip repositories.
however, even after manually correcting the pytables syntax in the source code i run into problems.

while groopM parse now finally seems to work, groopM core exits with the following error: ```IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices```

I have no idea if this is a problem with the exact numpy version, or something else.

**Comment by minillinim** [comment]
Hi there. 

I worked on GroopM quite a few years back and since then I've moved away from a career in Science and this code is sadly a bit stale. I've had ambitions to make it work well again but my regular job makes it hard to find the time to do that. It's often hard to even find the time to reply to issues on this and the other projects I used to maintain. I still believe the idea underlying this project is sound and there's some good parts of this code base, but there's also some embarrassingly naive parts too. I think that if anyone were intending on using this in 2022 then it'd probably take a fair amount of work to make it humm along. That said, if anyone wanted to embark on trying to carve out what's good here and improve on what's not then I'd be happy to pitch in - I'm a much better coder these days, but I'd be setting myself up for failure if I gave the impression I had the available time to  go over the code alone and make it workable. I'm sorry that this is probably not the reply you were hoping for.

**Comment by jvollme** [comment]
ok i understand. But do you perhaps have a pointer to the most recent working Fork, Branch and Commit? SOME version of it seems to still be in occasional use, but i just can't find which. The main branches of all forks i can find are definitively non-functional at the moment...
Or failing that: could you forward me the contact of someone who is still working on groopm2? I seems someone is still working on it as it has been used in the following assessment paper: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03667-3 and also in other more recent publications. However, so far i have received no ansers from the corresponding authors on how they achieved a functional groopm2 installation, nor from the maintainers of any of the other forks i could find...

**Comment by jvollme** [comment]
ok i finally found a way to get a functional installation! The main branch of this fork seems to be ok when using that method.
For anybody else with the same problem as me: here is the [gist with more or less detailed instructions](https://gist.github.com/jvollme/e1a511cee9349f87a446efd48be2c248)
However, I could not manage to get the python3 branch to run, just the python2 version
